vim.g.wiki_root = "/home/jonputer/Documents/wikis/wiki"
vim.opt.tabstop = 4
vim.opt.shiftwidth = 4
vim.opt.expandtab = true
vim.opt.relativenumber = true
vim.opt.number = true
vim.g.clipboard = "xclip"
vim.o.colorcolumn = tostring(math.floor(vim.o.columns * 0.9))
vim.opt.guicursor = ""
vim.g.netrw_liststyle = "0"
vim.g.netrw_banner = "0"
vim.g.netrw_winsize = 85
vim.g.netrw_altv = 1
vim.opt.termguicolors = true
