--vim.keymap.set("n", "-", ":Explore<CR>")
vim.keymap.set("n", "0", "^")
vim.keymap.set("n", ",", ";")
vim.keymap.set("n", "<leader>l", "$")
vim.keymap.set("n", "<leader>h", "^")
vim.keymap.set("n", "<C-j>", ":bp<CR>")
vim.keymap.set("n", "<C-k>", ":bn<CR>")
vim.keymap.set("n", "<leader>fd", ":bd<CR>")
vim.keymap.set("t", "<esc><esc>", "<c-\\><c-n>")
vim.keymap.set("n", "sl", function() vim.lsp.buf.hover() end)
vim.keymap.set("n", "sj", function() vim.lsp.buf.declaration() end)
vim.keymap.set("n", "sk", function() vim.lsp.buf.definition() end)
vim.keymap.set("n", "sh", function() vim.lsp.buf.format() end)
vim.keymap.set({"n", "t"}, "<C-Left>", function() vim.cmd"vertical resize -10" end)
vim.keymap.set({"n", "t"}, "<C-Right>", function() vim.cmd"vertical resize +10" end)
vim.keymap.set({"n", "t"}, "<C-Up>", function() vim.cmd"resize -5" end)
vim.keymap.set({"n", "t"}, "<C-Down>", function() vim.cmd"resize +5" end)
vim.keymap.set("n", "K", ":normal o<esc>k")
vim.keymap.set("n", "=", "@:")
vim.keymap.set("i", "<C-h>", "<C-o>h")
vim.keymap.set("i", "<C-j>", "<C-o>j")
vim.keymap.set("i", "<C-k>", "<C-o>k")
vim.keymap.set("i", "<C-l>", "<C-o>l")
vim.keymap.set("i", "<C-e>", "<C-o>A")
vim.keymap.set("i", "<C-a>", "<C-o>0")
vim.keymap.set("i", "<C-i>", "<c-o>ciw")
vim.keymap.set("i", "<C-f>", function()
    local key = vim.fn.nr2char(vim.fn.getchar())
    vim.cmd(string.format("<esc>f%sa", key))
end)
vim.keymap.set("i", "<C-f>", function()
    local key = vim.fn.nr2char(vim.fn.getchar())
    vim.cmd(string.format("<esc>F%sa", key))
end)
vim.keymap.set("i", "<C-d>", "<esc>;a")




vim.keymap.set("n","<leader>j", function()
    local count = vim.v.count > 0 and vim.v.count or 1
    local ret, _ = pcall(vim.cmd.argument, count)
    if not ret then
        print("Not a valid index")
    end
    print(string.format("[%s]", vim.fn.expand("%")))
end, { desc = "change to the file in the arglist" })
vim.keymap.set("n","<leader>ga", function() vim.cmd.argadd(vim.fn.expand("%")) end, { desc = "Add the current file to the arglist" })
vim.keymap.set("n","<leader>gr", function() vim.cmd.argdel(vim.fn.expand("%")) end, { desc = "Remove the current file from the arglist" })
vim.keymap.set("n","<C-l>", function() pcall(vim.cmd.next) end, { desc = "Move left in the arglist(towards the end)" })
vim.keymap.set("n","<C-h>", function() pcall(vim.cmd.prev) end, { desc = "Move right in the arglist(towards the begining)" })
vim.keymap.set("n","<leader>b", function() vim.cmd("args") end, { desc = "Show args list" })
vim.keymap.set("n","<C-b>", ":norm gUiw<CR>", { desc = "Make the word under the cursor all upper case" })
