--vim.keymap.set("n", "-", ":Explore<CR>")
vim.keymap.set("n", "0", "^")
vim.keymap.set("n", ",", ";")
vim.keymap.set("n", "<leader>l", "$")
vim.keymap.set("n", "<leader>h", "^")
vim.keymap.set("n", "<C-j>", ":bp<CR>")
vim.keymap.set("n", "<C-k>", ":bn<CR>")
vim.keymap.set("n", "<leader>fd", ":bd<CR>")
vim.keymap.set("t", "<esc><esc>", "<c-\\><c-n>")
vim.keymap.set("n", "sl", function() vim.lsp.buf.hover() end)
vim.keymap.set("n", "sj", function() vim.lsp.buf.declaration() end)
vim.keymap.set("n", "sk", function() vim.lsp.buf.definition() end)
vim.keymap.set("n", "sh", function() vim.lsp.buf.format() end)
vim.keymap.set({"n", "t"}, "<C-Left>", function() vim.cmd"vertical resize -10" end)
vim.keymap.set({"n", "t"}, "<C-Right>", function() vim.cmd"vertical resize +10" end)
vim.keymap.set({"n", "t"}, "<C-Up>", function() vim.cmd"resize -5" end)
vim.keymap.set({"n", "t"}, "<C-Down>", function() vim.cmd"resize +5" end)
vim.keymap.set("n", "K", ":normal o<esc>k")
vim.keymap.set("n", "=", "@:")
vim.keymap.set("i", "<C-h>", "<esc>ha")
vim.keymap.set("i", "<C-j>", "<esc>ja")
vim.keymap.set("i", "<C-k>", "<esc>ka")
vim.keymap.set("i", "<C-l>", "<esc>la")
vim.keymap.set("i", "<C-e>", "<esc>A")
vim.keymap.set("i", "<C-a>", "<esc>0i")
vim.keymap.set("i", "<C-i>", "<esc>ciw")
vim.keymap.set("i", "<C-f>", function()
    local key = vim.fn.nr2char(vim.fn.getchar())
    vim.cmd(string.format("<esc>f%sa", key))
end)
vim.keymap.set("i", "<C-f>", function()
    local key = vim.fn.nr2char(vim.fn.getchar())
    vim.cmd(string.format("<esc>F%sa", key))
end)
vim.keymap.set("i", "<C-d>", "<esc>;a")
