local FOLLOW = require("followMdLinks")
local TEMPLATES = require("templates")
local FILE = require("managefile")
local META = require("metadata")
local CMD = require("cmdfunc")
local TOPICMOVE = require("topicmove")
local MCHANGE = require("metachange")
local NOTE = require("notefunc")

-- Configurando as funções como comandos do vim
vim.api.nvim_create_user_command('Template', TEMPLATES.template_new_file, { desc = "template for any file" })
vim.api.nvim_create_user_command('Html', TEMPLATES.template_html, { desc = "Cria um template para um arquivo html", nargs = 0 })
vim.api.nvim_create_user_command('Date', TEMPLATES.template_date, { desc = "Cria um template com a data de hoje" })
vim.api.nvim_create_user_command('FollowMdLinks', FOLLOW.followMdLinks , {})
vim.api.nvim_create_user_command('Teste', function() end, {})
vim.api.nvim_create_user_command('Mk', function() FILE.newfile() end, {})
vim.api.nvim_create_user_command('Comment', function() vim.cmd("'<,'>s/^/-- /") end, { desc="Comenta com --"})
vim.api.nvim_create_user_command('DelFile', FILE.DeleteFile, { desc="deleta o arquivo atual" })
vim.api.nvim_create_user_command('ChangeFile', FILE.ChangeNode, { desc="Muda o nome do arquivo atual" })
vim.api.nvim_create_user_command("Floaterminal", CMD.floaterminal, {})
vim.api.nvim_create_user_command('Meta', META.Main, { desc="metadata search" , nargs="*"})
vim.api.nvim_create_user_command('Note', NOTE.main, { desc="New Note"})



-- remaps
vim.keymap.set('n', '<Leader>tt', ":Template<CR>", {desc="metadata template"})
vim.keymap.set("n", "<leader>td", ":Date", {silent = true, noremap = true, desc = "date template"})
vim.keymap.set('n', '<CR>', FOLLOW.followMdLinks, { noremap = true })
vim.keymap.set('n', '<BS>', ":e #<CR>", {})
vim.keymap.set('n', '<Leader>fn', function() FILE.newfile() end, { desc = "novo arquivo" })
vim.keymap.set('n', '<Leader>fd', ':DelFile<CR>', { desc="deleta o arquivo atual"})
vim.keymap.set('n', '<Leader>fr', ':ChangeFile<CR>', { desc="Muda o nome do arquivo atual"})
vim.keymap.set({'n', 't'}, '<space>tt', CMD.floaterminal , {})
vim.keymap.set('n', '<Leader>mg', function() META.searchMetadataVerbose() end, { desc="verbose greedy metadata search"})
vim.keymap.set('n', '<Leader>mn', function() META.searchMetadataVerbose({greedy=false}) end, { desc="verbose nongreedy metadata search"})
vim.keymap.set('n', '<Leader>ms', ':Meta<CR>', { desc="Metadata search"})
vim.keymap.set('n', '<Leader>ml', META.searchLinks, { desc="Search with link keyword"})
vim.keymap.set('n', '<Leader>fm', TOPICMOVE.topicmove, { desc="move .assuntos dir to a topic"})
vim.keymap.set('n', '<Leader>mc', MCHANGE.metachange, { desc="change metadata fields" })
vim.keymap.set('n', '<space>n', ":Note<CR>", {desc="New note"})
