local follow = require("followMdLinks")
local tmp = require("templates")
local fs = require("managefile")
local mt = require("metadata")
local cmd = require("cmdfunc")
local nt = require("notefunc")

-- Configurando as funções como comandos do vim
vim.api.nvim_create_user_command('Template', tmp.template_new_file, { desc = "template for any file" })
vim.api.nvim_create_user_command('Html', tmp.template_html, { desc = "Cria um template para um arquivo html", nargs = 0 })
vim.api.nvim_create_user_command('Date', tmp.template_date, { desc = "Cria um template com a data de hoje" })
vim.api.nvim_create_user_command('FollowMdLinks', follow.followMdLinks , {})
vim.api.nvim_create_user_command('Teste', function() end, {})
vim.api.nvim_create_user_command('Touch', function(opts) vim.cmd([[e expand('%:p:h')."/]]..opts.args..'"') end, {nargs=1})
vim.api.nvim_create_user_command('Comment', function() vim.cmd("'<,'>s/^/-- /") end, { desc="Comenta com --"})
vim.api.nvim_create_user_command('DelFile', fs.DeleteFile, { desc="deleta o arquivo atual" })
vim.api.nvim_create_user_command('ChangeFile', fs.ChangeNode, { desc="Muda o nome do arquivo atual" })
vim.api.nvim_create_user_command('Floaterminal', cmd.floaterminal, {})
vim.api.nvim_create_user_command('Note', nt.main, { desc="New Note"})
vim.api.nvim_create_user_command('Push', mt.push.Push, { desc="Push files in the topic dir to the link dir", nargs=1})
vim.api.nvim_create_user_command('Index', mt.index.linksIndex, { desc="Wiki Index", nargs="*"})
vim.api.nvim_create_user_command('Mt', mt.pickers.search, { desc="Metadata search", nargs=1})
vim.api.nvim_create_user_command('Mtc', mt.change.change, { desc="Change metadata in the current buffer", nargs=1})
vim.api.nvim_create_user_command("Qf", function() vim.cmd([[caddexpr expand("%") . ":" . line(".") . ":" . col(".") . ":" . getline(".")]]) end , { desc="add line to qf list"})
vim.api.nvim_create_user_command("File", function(opts) vim.cmd([[e ]]..vim.fs.joinpath(vim.g.wiki_root, ".assuntos", opts.args)) end, {desc = "new Md file", nargs=1})
vim.api.nvim_create_user_command("Qfile", function(opts) vim.cmd([[vsplit | e ]]..vim.fs.joinpath(vim.g.wiki_root, ".assuntos", opts.args)) end, {desc = "new Md file with split", nargs=1})
vim.api.nvim_create_user_command("Exlink", mt.data.linkExists, {desc = "new Md file with split", nargs=1})
vim.api.nvim_create_user_command("Extag", mt.data.tagExists, {desc = "new Md file with split", nargs=1})



-- remaps
vim.keymap.set('n', '<Leader>tt', ":Template<CR>", {desc="metadata template"})
vim.keymap.set('n', '<leader>td', ':Date', {silent = true, noremap = true, desc = 'date template'})
vim.keymap.set('n', '<CR>', follow.followMdLinks, { noremap = true })
vim.keymap.set('n', '<BS>', ":e #<CR>", {})
vim.keymap.set('n', '<Leader>fn', function() fs.newfile() end, { desc = 'novo arquivo' })
vim.keymap.set('n', '<Leader>fd', ':DelFile<CR>', { desc='deleta o arquivo atual'})
vim.keymap.set('n', '<Leader>fr', ':ChangeFile<CR>', { desc='Muda o nome do arquivo atual'})
vim.keymap.set({'n', 't'}, '<space>tt', cmd.floaterminal , {})
vim.keymap.set('n', '<space>n', ':Note<CR>', {desc='New note'})
vim.keymap.set('n', '<Leader>e', function() mt.index.linksIndex() end, {desc='Wiki Index'})
vim.keymap.set('n', '<Leader>pl', function() mt.pickers.accessMemory() end, {desc='Wiki Index'})
vim.keymap.set("n", "<Leader>q", function() vim.cmd([[caddexpr expand("%") . ":" . line(".") . ":" . col(".") . ":" . getline(".")]]) end , { desc="add line to qf list"})
